# Generated by Django 2.2.12 on 2020-09-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0011_auto_20200807_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariesuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
