# Generated by Django 2.2.13 on 2020-09-24 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0012_ariesuser_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='indyproofrequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indyproofrequest',
            name='agent',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='indyproofrequest',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indyproofrequest',
            name='expiration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
