# Generated by Django 2.2.13 on 2020-09-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0013_auto_20200924_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indyproofrequest',
            old_name='creation_date',
            new_name='creation',
        ),
        migrations.RenameField(
            model_name='indyproofrequest',
            old_name='expiration_date',
            new_name='expiration',
        ),
    ]
