# Generated by Django 2.2.13 on 2020-09-24 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0015_auto_20200924_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indyproofrequest',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='indyproofrequest',
            name='expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
