# Generated by Django 2.2.13 on 2020-10-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0017_agentconversation_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indyproofrequest',
            name='proof_req_name',
            field=models.CharField(max_length=400),
        ),
    ]
