# Generated by Django 2.2.13 on 2020-10-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0018_auto_20201013_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariesuser',
            name='pubkey',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
