# Generated by Django 2.2.13 on 2020-10-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0020_auto_20201020_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariesuser',
            name='cpf',
            field=models.CharField(max_length=150),
        ),
    ]
