# Generated by Django 2.2.13 on 2020-10-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aries_community', '0022_auto_20201021_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ariesuser',
            old_name='cidade_emissao',
            new_name='emissao',
        ),
    ]
